baseURL = 'https://andy.sb'
languageCode = 'en-us'
title = "Andy Sukowski-Bang"
theme = 'nojs'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2

  [[menus.main]]
    name = 'PGP'
    pageRef = '/pgp'
    weight = 3

  [[menus.main]]
    name = 'XMR'
    pageRef = '/xmr'
    weight = 4

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 5
